import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { getLocale } from "next-intl/server";
import { Button } from "@/components/ui/Button";
import { Reveal, RevealGroup, RevealItem } from "@/components/ui/Reveal";
import { Section } from "@/components/ui/Section";
import { ServiceIcon } from "@/components/ui/ServiceIcon";
import { CONSULTANCY_DETAILS, getConsultancyMenuItem } from "@/lib/consultancy";
import { localizeConsultancy, localizeMenuItem } from "@/i18n/consultancy-ar";
import { JsonLd, breadcrumbSchema, buildMetadata } from "@/lib/seo";

export async function generateMetadata() {
  const ar = (await getLocale()) === "ar";
  return buildMetadata({ title: ar ? "استشارات التقنية والمنتجات" : "Technology & Product Consultancy", description: ar ? "استشارات عملية في التقنية والمنتجات والذكاء الاصطناعي والتصميم والعمليات للفرق التي تستعد لقرارات مهمة." : "Practical technology, product, AI, design, and operations consultancy for teams planning their next critical decision.", path: "/consultancy" });
}

export default async function ConsultancyPage() {
  const locale = await getLocale();
  const ar = locale === "ar";
  return <div className="consultancy-page consultancy-page--redesign">
    <section className="consultancy-landing-hero overflow-hidden bg-ink-950 text-ontext"><div aria-hidden className="consultancy-landing-hero__word">{ar ? "الاستشارات" : "Consultancy"}</div><div className="shell consultancy-landing-hero__inner"><Reveal kind="flat" className="consultancy-landing-hero__content"><span className="consultancy-landing-hero__index">{ar ? "01 / الاستشارات" : "01 / Advisory"}</span><h1 className="consultancy-landing-hero__title">{ar ? "طريق أوضح لاتخاذ " : "A clearer path through "}<span>{ar ? "القرارات التقنية المعقدة." : "complex technical decisions."}</span></h1><p className="consultancy-landing-hero__lead">{ar ? "تساعد باراكود الفرق على تحويل الغموض إلى توجه عملي، من خلال مشورة مستقلة تنطلق من النتائج التي تريد تحقيقها." : "Barakode helps teams turn uncertainty into a practical direction, with independent advice grounded in the outcome they need to reach."}</p><div className="consultancy-landing-hero__actions"><Button href="/contact?intent=consultancy" size="lg" variant="onDark" arrow>{ar ? "ناقش تحديك معنا" : "Discuss Your Challenge"}</Button><Button href="/case-studies" size="lg" variant="onDarkGhost">{ar ? "اطلع على أعمالنا" : "View Our Work"}</Button></div></Reveal><Reveal kind="right" className="consultancy-landing-hero__ledger"><span>{ar ? "دعم القرار" : "Decision support"}</span><span>{ar ? "12 مجالًا استشاريًا" : "12 advisory areas"}</span><span>{ar ? "توجيه مستقل" : "Independent guidance"}</span></Reveal></div></section>
    <Section surface="paper" aria-labelledby="consultancy-overview-heading" className="consultancy-landing-intro"><div className="shell consultancy-landing-intro__grid"><Reveal><p className="consultancy-landing-intro__label">{ar ? "نهجنا الاستشاري" : "The advisory practice"}</p><h2 id="consultancy-overview-heading">{ar ? "القرار المهم يستحق عملًا استشاريًا مركزًا." : "A focused decision deserves a focused engagement."}</h2></Reveal><Reveal kind="right" className="consultancy-landing-intro__copy"><p className="text-lead text-text-2">{ar ? "نبدأ كل تعاون بالقرار الذي يحتاج فريقك إلى اتخاذه، لا بحل جاهز مسبقًا." : "Every engagement begins with the decision your team needs to make, not a pre-packaged solution."}</p><p className="mt-6 measure text-text-3">{ar ? "نجمع أصحاب العلاقة والقيود والأنظمة والخيارات في صورة واحدة، ثم نحولها إلى توجه واضح يستطيع فريقك تنفيذه." : "We bring the right people, constraints, systems, and trade-offs into view—then turn them into a clear direction that your team can own."}</p></Reveal></div><div className="shell"><Reveal className="consultancy-landing-principles"><p>{ar ? "وضوح يتحول إلى عمل." : "Clarity your team can act on."}</p><ul><li>{ar ? "فهم مشترك للقرار الأهم." : "Shared context around the decision that matters."}</li><li>{ar ? "أولويات ترتبط بالنتيجة، لا بالافتراضات." : "Priorities tied to the outcome, not assumptions."}</li><li>{ar ? "توصية عملية ومسار واضح للمضي قدمًا." : "A practical recommendation and route forward."}</li></ul></Reveal></div></Section>
    <Section surface="ink" aria-labelledby="areas-heading" className="consultancy-landing-areas"><div className="shell"><Reveal className="consultancy-landing-areas__head"><p className="consultancy-landing-areas__label">{ar ? "اختر مجال القرار" : "Choose a decision"}</p><h2 id="areas-heading">{ar ? "المجال الاستشاري نقطة البداية. " : "The advisory area is the starting point. "}<span>{ar ? "والنتيجة تبقى أمامنا." : "The outcome stays in view."}</span></h2><p>{ar ? "اختر المجال المناسب لتتعرف على إطار القرار والمخرجات المتوقعة والطريق العملي للمضي قدمًا." : "Choose an advisory area to see the decision framework, expected outcomes, and practical route forward."}</p></Reveal><RevealGroup as="ol" className="consultancy-landing-areas__grid">{CONSULTANCY_DETAILS.map((source, index) => { const originalItem = getConsultancyMenuItem(source.slug); const detail = ar ? localizeConsultancy(source) : source; const item = originalItem && localizeMenuItem(originalItem, locale); return item && <RevealItem key={detail.slug} as="li"><Link href={item.href} className="consultancy-area-card group"><span className="consultancy-area-card__top"><span>{String(index + 1).padStart(2, "0")}</span><ServiceIcon name={item.icon} className="size-5" /></span><span className="consultancy-area-card__title">{item.label}</span><span className="consultancy-area-card__copy">{detail.overview}</span><span className="consultancy-area-card__cta">{ar ? "اكتشف الاستشارة" : "Explore advisory"} <ArrowRight aria-hidden className="size-4" /></span></Link></RevealItem>; })}</RevealGroup></div></Section>
    <Section surface="paper" aria-labelledby="consultancy-next-heading" className="consultancy-next-section"><div className="shell consultancy-next-section__grid"><Reveal><h2 id="consultancy-next-heading">{ar ? "لنحدد ملامح قرارك التالي." : "Bring the next decision into focus."}</h2><p className="mt-6 measure text-lead text-text-2">{ar ? "ابدأ بالسؤال الذي يشغل فريقك اليوم. سنساعدك على رؤية الطريق إلى الأمام بوضوح." : "Start with the question in front of your team. We will help make the route forward visible."}</p><Button href="/contact?intent=consultancy" size="lg" className="mt-9" arrow>{ar ? "ابدأ الحديث معنا" : "Start a Conversation"}</Button></Reveal><Reveal kind="right" className="consultancy-decision-object" aria-hidden><div className="consultancy-decision-object__scene"><div className="consultancy-decision-object__plane consultancy-decision-object__plane--top" /><div className="consultancy-decision-object__plane consultancy-decision-object__plane--middle" /><div className="consultancy-decision-object__plane consultancy-decision-object__plane--base" /><div className="consultancy-decision-object__core" /><span className="consultancy-decision-object__axis consultancy-decision-object__axis--x" /><span className="consultancy-decision-object__axis consultancy-decision-object__axis--y" /></div></Reveal></div></Section>
    <JsonLd data={breadcrumbSchema([{ name: ar ? "الرئيسية" : "Home", path: "/" }, { name: ar ? "الاستشارات" : "Consultancy", path: "/consultancy" }])} />
  </div>;
}
