import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Reveal, RevealGroup, RevealItem } from "@/components/ui/Reveal";
import { Section } from "@/components/ui/Section";
import { ServiceIcon } from "@/components/ui/ServiceIcon";
import { CONSULTANCY_DETAILS, getConsultancyMenuItem } from "@/lib/consultancy";
import { JsonLd, breadcrumbSchema, buildMetadata } from "@/lib/seo";

export const metadata = buildMetadata({ title: "Technology & Product Consultancy", description: "Practical technology, product, AI, design, and operations consultancy for teams planning their next critical decision.", path: "/consultancy" });

export default function ConsultancyPage() {
  return <div className="consultancy-page consultancy-page--redesign">
    <section className="consultancy-landing-hero overflow-hidden bg-ink-950 text-ontext"><div aria-hidden className="consultancy-landing-hero__word">Consultancy</div><div className="shell consultancy-landing-hero__inner"><Reveal kind="flat" className="consultancy-landing-hero__content"><span className="consultancy-landing-hero__index">01 / Advisory</span><h1 className="consultancy-landing-hero__title">A clearer path through <span>complex technical decisions.</span></h1><p className="consultancy-landing-hero__lead">Barakode helps teams turn uncertainty into a practical direction, with independent advice grounded in the outcome they need to reach.</p><div className="consultancy-landing-hero__actions"><Button href="/contact?intent=consultancy" size="lg" variant="onDark" arrow>Discuss Your Challenge</Button><Button href="/case-studies" size="lg" variant="onDarkGhost">View Our Work</Button></div></Reveal><Reveal kind="right" className="consultancy-landing-hero__ledger"><span>Decision support</span><span>12 advisory areas</span><span>Independent guidance</span></Reveal></div></section>
    <Section surface="paper" aria-labelledby="consultancy-overview-heading" className="consultancy-landing-intro"><div className="shell consultancy-landing-intro__grid"><Reveal><p className="consultancy-landing-intro__label">The advisory practice</p><h2 id="consultancy-overview-heading">A focused decision deserves a focused engagement.</h2></Reveal><Reveal kind="right" className="consultancy-landing-intro__copy"><p className="text-lead text-text-2">Every engagement begins with the decision your team needs to make, not a pre-packaged solution.</p><p className="mt-6 measure text-text-3">We bring the right people, constraints, systems, and trade-offs into view—then turn them into a clear direction that your team can own.</p></Reveal></div><div className="shell"><Reveal className="consultancy-landing-principles"><p>Clarity your team can act on.</p><ul><li>Shared context around the decision that matters.</li><li>Priorities tied to the outcome, not assumptions.</li><li>A practical recommendation and route forward.</li></ul></Reveal></div></Section>
    <Section surface="ink" aria-labelledby="areas-heading" className="consultancy-landing-areas"><div className="shell"><Reveal className="consultancy-landing-areas__head"><p className="consultancy-landing-areas__label">Choose a decision</p><h2 id="areas-heading">The advisory area is the starting point. <span>The outcome stays in view.</span></h2><p>Choose an advisory area to see the decision framework, expected outcomes, and practical route forward.</p></Reveal><RevealGroup as="ol" className="consultancy-landing-areas__grid">{CONSULTANCY_DETAILS.map((detail, index) => { const item = getConsultancyMenuItem(detail.slug); return item && <RevealItem key={detail.slug} as="li"><Link href={item.href} className="consultancy-area-card group"><span className="consultancy-area-card__top"><span>{String(index + 1).padStart(2, "0")}</span><ServiceIcon name={item.icon} className="size-5" /></span><span className="consultancy-area-card__title">{item.label}</span><span className="consultancy-area-card__copy">{detail.overview}</span><span className="consultancy-area-card__cta">Explore advisory <ArrowRight aria-hidden className="size-4" /></span></Link></RevealItem>; })}</RevealGroup></div></Section>
    <Section surface="paper" aria-labelledby="consultancy-next-heading" className="consultancy-next-section"><div className="shell consultancy-next-section__grid"><Reveal><h2 id="consultancy-next-heading">Bring the next decision into focus.</h2><p className="mt-6 measure text-lead text-text-2">Start with the question in front of your team. We will help make the route forward visible.</p><Button href="/contact?intent=consultancy" size="lg" className="mt-9" arrow>Start a Conversation</Button></Reveal><Reveal kind="right" className="consultancy-decision-object" aria-hidden><div className="consultancy-decision-object__scene"><div className="consultancy-decision-object__plane consultancy-decision-object__plane--top" /><div className="consultancy-decision-object__plane consultancy-decision-object__plane--middle" /><div className="consultancy-decision-object__plane consultancy-decision-object__plane--base" /><div className="consultancy-decision-object__core" /><span className="consultancy-decision-object__axis consultancy-decision-object__axis--x" /><span className="consultancy-decision-object__axis consultancy-decision-object__axis--y" /></div></Reveal></div></Section>
    <JsonLd data={breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Consultancy", path: "/consultancy" }])} />
  </div>;
}
