import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Check, Quote } from "lucide-react";
import { Accordion } from "@/components/ui/Accordion";
import { Button } from "@/components/ui/Button";
import { Reveal, RevealGroup, RevealItem } from "@/components/ui/Reveal";
import { Marker, Section } from "@/components/ui/Section";
import { ServiceIcon } from "@/components/ui/ServiceIcon";
import { CONSULTANCY_DETAILS, getConsultancyDetail, getConsultancyMenuItem } from "@/lib/consultancy";
import { JsonLd, breadcrumbSchema, buildMetadata, faqSchema, serviceSchema } from "@/lib/seo";

const CONSULTANCY_IMAGES: Record<string, { src: string; alt: string }> = {
  "it-consultation": { src: "/images/consultancy/it-consultation.webp", alt: "Connected infrastructure pathways for IT consultation" },
  "it-outsourcing": { src: "/images/consultancy/it-outsourcing.webp", alt: "Connected delivery pathways for IT outsourcing consultancy" },
  "managed-it": { src: "/images/consultancy/managed-it.webp", alt: "Protected infrastructure for managed IT services consultancy" },
  "design-consultancy": { src: "/images/consultancy/design-consultancy.webp", alt: "Product-shaping forms for design consultancy" },
  "ai-data-strategy": { src: "/images/consultancy/ai-data-strategy.webp", alt: "Data streams converging into an AI strategy core" },
  "digital-transformation": { src: "/images/consultancy/digital-transformation.webp", alt: "Modern operating layers for digital transformation consultancy" },
  "product-strategy": { src: "/images/consultancy/product-strategy.webp", alt: "A product decision compass and priority roadmap" },
  "tech-strategy": { src: "/images/consultancy/tech-strategy.webp", alt: "Technology architecture pathways for strategy consultancy" },
  "devops-consulting": { src: "/images/consultancy/devops-consulting.webp", alt: "Resilient delivery pathways for DevOps consultancy" },
  "microservices-consulting": { src: "/images/consultancy/microservices-consulting.webp", alt: "Connected independent modules for microservices consultancy" },
  "iot-consultancy": { src: "/images/consultancy/iot-consultancy.webp", alt: "A connected physical sensing ecosystem for IoT consultancy" },
  "business-intelligence": { src: "/images/consultancy/business-intelligence.webp", alt: "Analytical data layers resolving into a business decision" },
};

export function generateStaticParams() { return CONSULTANCY_DETAILS.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const detail = getConsultancyDetail(slug); const item = getConsultancyMenuItem(slug); return detail && item ? buildMetadata({ title: detail.metaTitle, description: detail.metaDescription, path: item.href }) : {}; }

export default async function ConsultancyDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const detail = getConsultancyDetail(slug); const item = getConsultancyMenuItem(slug); if (!detail || !item) notFound();
  const image = CONSULTANCY_IMAGES[slug];
  const related = detail.related.map((relatedSlug) => ({ detail: getConsultancyDetail(relatedSlug), item: getConsultancyMenuItem(relatedSlug) })).filter((entry): entry is { detail: NonNullable<typeof entry.detail>; item: NonNullable<typeof entry.item> } => Boolean(entry.detail && entry.item));
  return <div className="consultancy-detail-page">
    <section className="consultancy-detail-hero relative overflow-hidden bg-ink-950 text-ontext"><div className="shell"><Reveal kind="flat" className="mx-auto max-w-4xl text-center"><p className="font-mono text-marker tracking-[.16em] text-accent-bright uppercase">Consultancy / {item.label}</p><h1 className="mt-5 text-d1 text-white">{detail.hero.heading} <span className="text-accent-bright">{detail.hero.accent}</span></h1><p className="measure mx-auto mt-7 text-lead text-ontext-2">{detail.hero.body}</p><div className="mt-9 flex w-full flex-wrap justify-center gap-3"><Button href={`/contact?intent=${slug}`} size="lg" variant="onDark" arrow>Discuss {item.label}</Button><Button href="#overview" size="lg" variant="onDarkGhost">Explore advisory</Button></div></Reveal></div></section>
    <Section id="overview" surface="paper" aria-labelledby="overview-heading"><div className="shell grid items-start gap-10 lg:grid-cols-[.85fr_1.15fr]"><Reveal><Marker>About this advisory</Marker><h2 id="overview-heading" className="mt-5 max-w-[15ch] text-d2 text-text">A focused decision deserves a focused engagement.</h2><p className="measure mt-6 text-lead text-text-2">{detail.overview}</p><p className="measure mt-4 text-text-3">{detail.challenge}</p></Reveal><Reveal kind="right"><div className="overflow-hidden rounded-[var(--radius-lg)] border border-rule bg-white shadow-e2"><div className="relative aspect-[16/10]">{image && <Image src={image.src} alt={image.alt} fill sizes="(min-width: 1024px) 52vw, 100vw" className="object-cover" />}</div><div className="p-6 sm:p-8"><ServiceIcon name={item.icon} className="size-7 text-accent" /><p className="mt-6 font-display text-2xl leading-tight font-semibold text-text sm:text-3xl">Clarity your team can act on.</p><p className="mt-4 text-text-3">A well-framed direction, transparent trade-offs, and a practical route to the next milestone.</p></div></div></Reveal></div></Section>
    <Section surface="paper" aria-labelledby="outcomes-heading" className="consultancy-outcomes"><div className="shell"><Reveal className="max-w-3xl"><Marker>What you leave with</Marker><h2 id="outcomes-heading" className="mt-4 text-d2 text-text">Clarity that is ready to act on.</h2></Reveal><RevealGroup as="ol" className="consultancy-outcomes__list mt-12">{detail.outcomes.map((outcome, index) => <RevealItem key={outcome} as="li"><div className="consultancy-outcomes__item"><span>{String(index + 1).padStart(2, "0")}</span><h3>{outcome}</h3></div></RevealItem>)}</RevealGroup></div></Section>
    <Section surface="ink"><div className="shell grid items-start gap-10 lg:grid-cols-[.72fr_1.28fr]"><Reveal><span className="font-mono text-marker font-medium tracking-[.16em] text-accent-bright uppercase">Client feedback</span><h2 className="mt-5 max-w-[12ch] text-d2 text-white">Trusted through the details.</h2></Reveal><Reveal kind="right"><figure className="rounded-[var(--radius-lg)] border border-white/15 bg-white/[.05] p-8 sm:p-10"><Quote aria-hidden className="size-8 text-accent-bright" /><blockquote className="mt-6 font-display text-xl leading-snug text-white sm:text-2xl">&ldquo;The Barakode team delivered ahead of schedule and consistently exceeded our expectations. Their expertise and commitment to quality have made them a trusted partner for our business.&rdquo;</blockquote><figcaption className="mt-7 pt-2 text-sm text-ontext-2"><span className="block font-medium text-white">Adam Lewis</span>Founder & CEO, iConsult</figcaption></figure></Reveal></div></Section>
    <Section surface="paper" aria-labelledby="focus-heading"><div className="shell"><Reveal><Marker>Where we focus</Marker><h2 id="focus-heading" className="mt-5 max-w-[15ch] text-d2 text-text">The signals and people around this decision.</h2></Reveal><div className="mt-10 grid gap-8 lg:grid-cols-2"><RevealGroup as="ul" className="grid gap-3">{detail.signals.map((signal) => <RevealItem key={signal} as="li" className="rounded-[var(--radius-sm)] border border-rule bg-paper-raised p-5 text-text-2"><Check aria-hidden className="mr-3 inline size-4 text-accent" />{signal}</RevealItem>)}</RevealGroup><RevealGroup as="ul" className="grid gap-3">{detail.audience.map((audience) => <RevealItem key={audience} as="li" className="rounded-[var(--radius-sm)] border border-rule bg-paper-raised p-5 text-text-2"><ServiceIcon name={item.icon} className="mr-3 inline size-4 text-accent" />{audience}</RevealItem>)}</RevealGroup></div></div></Section>
    <Section surface="paper" aria-labelledby="approach-heading"><div className="shell grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><Reveal><Marker>Our approach</Marker><h2 id="approach-heading" className="mt-5 max-w-[13ch] text-d2 text-text">A structured path to a defensible decision.</h2></Reveal><RevealGroup as="ol" className="grid gap-3 sm:grid-cols-2">{detail.steps.map((step, index) => <RevealItem key={step.title} as="li" className="rounded-[var(--radius-md)] border border-rule bg-paper-raised p-5 shadow-e1"><span className="font-mono text-xs text-accent-ink">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-5 text-lg font-semibold text-text">{step.title}</h3><p className="mt-2 text-sm leading-relaxed text-text-3">{step.detail}</p></RevealItem>)}</RevealGroup></div></Section>
    <Section surface="paper" aria-labelledby="faq-heading"><div className="shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><Reveal><Marker>Questions</Marker><h2 id="faq-heading" className="mt-5 max-w-[12ch] text-d2 text-text">The practical details, answered.</h2><Button href={`/contact?intent=${slug}`} size="lg" className="mt-8" arrow>Start a conversation</Button></Reveal><Reveal kind="right"><Accordion items={detail.faqs} /></Reveal></div></Section>
    {related.length > 0 && <Section surface="paper"><div className="shell"><Reveal><h2 className="max-w-[20ch] text-d3 text-text">Explore the next connected decision.</h2></Reveal><RevealGroup as="ul" className="mt-8 grid gap-3 md:grid-cols-3">{related.map(({ detail: relatedDetail, item: relatedItem }) => <RevealItem key={relatedItem.href} as="li"><Link href={relatedItem.href} className="group flex h-full items-center justify-between gap-5 rounded-[var(--radius-md)] border border-rule bg-white p-5 text-text shadow-e1 transition-[border-color,box-shadow,transform] duration-300 hover:-translate-y-0.5 hover:border-accent/60 hover:shadow-e2"><span><span className="block font-display font-semibold">{relatedItem.label}</span><span className="mt-1 block text-sm text-text-3">{relatedDetail.overview}</span></span><ArrowRight aria-hidden className="size-4 shrink-0 text-accent transition-transform group-hover:translate-x-1" /></Link></RevealItem>)}</RevealGroup></div></Section>}
    <JsonLd data={[serviceSchema({ name: item.label, description: detail.metaDescription, path: item.href }), breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Consultancy", path: "/consultancy" }, { name: item.label, path: item.href }]), faqSchema(detail.faqs)]} />
  </div>;
}
