import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Check, Quote } from "lucide-react";
import { Accordion } from "@/components/ui/Accordion";
import { Button } from "@/components/ui/Button";
import { Reveal, RevealGroup, RevealItem } from "@/components/ui/Reveal";
import { Marker, Section } from "@/components/ui/Section";
import { ServiceIcon } from "@/components/ui/ServiceIcon";
import { CONSULTANCY_DETAILS, getConsultancyDetail, getConsultancyMenuItem } from "@/lib/consultancy";
import { JsonLd, breadcrumbSchema, buildMetadata, faqSchema, serviceSchema } from "@/lib/seo";
import { getLocale } from "next-intl/server";
import { localizeConsultancy, localizeMenuItem } from "@/i18n/consultancy-ar";

const CONSULTANCY_IMAGES: Record<string, { src: string; alt: string }> = {
  "it-consultation": { src: "/images/consultancy/it-consultation.webp", alt: "Connected infrastructure pathways for IT consultation" },
  "it-outsourcing": { src: "/images/consultancy/it-outsourcing.webp", alt: "Connected delivery pathways for IT outsourcing consultancy" },
  "managed-it": { src: "/images/consultancy/managed-it.webp", alt: "Protected infrastructure for managed IT services consultancy" },
  "design-consultancy": { src: "/images/consultancy/design-consultancy.webp", alt: "Product-shaping forms for design consultancy" },
  "ai-data-strategy": { src: "/images/consultancy/ai-data-strategy.webp", alt: "Data streams converging into an AI strategy core" },
  "digital-transformation": { src: "/images/consultancy/digital-transformation.webp", alt: "Modern operating layers for digital transformation consultancy" },
  "product-strategy": { src: "/images/consultancy/product-strategy.webp", alt: "A product decision compass and priority roadmap" },
  "tech-strategy": { src: "/images/consultancy/tech-strategy.webp", alt: "Technology architecture pathways for strategy consultancy" },
  "devops-consulting": { src: "/images/consultancy/devops-consulting.webp", alt: "Resilient delivery pathways for DevOps consultancy" },
  "microservices-consulting": { src: "/images/consultancy/microservices-consulting.webp", alt: "Connected independent modules for microservices consultancy" },
  "iot-consultancy": { src: "/images/consultancy/iot-consultancy.webp", alt: "A connected physical sensing ecosystem for IoT consultancy" },
  "business-intelligence": { src: "/images/consultancy/business-intelligence.webp", alt: "Analytical data layers resolving into a business decision" },
};

export function generateStaticParams() { return CONSULTANCY_DETAILS.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const source = getConsultancyDetail(slug); const item = getConsultancyMenuItem(slug); const detail = source && (await getLocale()) === "ar" ? localizeConsultancy(source) : source; return detail && item ? buildMetadata({ title: detail.metaTitle, description: detail.metaDescription, path: item.href }) : {}; }

export default async function ConsultancyDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const source = getConsultancyDetail(slug); const originalItem = getConsultancyMenuItem(slug); if (!source || !originalItem) notFound();
  const locale = await getLocale(); const ar = locale === "ar"; const detail = ar ? localizeConsultancy(source) : source; const item = localizeMenuItem(originalItem, locale);
  const image = CONSULTANCY_IMAGES[slug];
  const related = detail.related.map((relatedSlug) => ({ detail: getConsultancyDetail(relatedSlug), item: getConsultancyMenuItem(relatedSlug) })).filter((entry): entry is { detail: NonNullable<typeof entry.detail>; item: NonNullable<typeof entry.item> } => Boolean(entry.detail && entry.item)).map(({ detail: relatedDetail, item: relatedItem }) => ({ detail: ar ? localizeConsultancy(relatedDetail) : relatedDetail, item: localizeMenuItem(relatedItem, locale) }));
  return <div className="consultancy-detail-page">
    <section className="consultancy-detail-hero relative overflow-hidden bg-ink-950 text-ontext"><div className="shell"><Reveal kind="flat" className="mx-auto max-w-4xl text-center"><p className="font-mono text-marker tracking-[.16em] text-accent-bright uppercase">{ar ? "الاستشارات" : "Consultancy"} / {item.label}</p><h1 className="mt-5 text-d1 text-white">{detail.hero.heading} <span className="text-accent-bright">{detail.hero.accent}</span></h1><p className="measure mx-auto mt-7 text-lead text-ontext-2">{detail.hero.body}</p><div className="mt-9 flex w-full flex-wrap justify-center gap-3"><Button href={`/contact?intent=${slug}`} size="lg" variant="onDark" arrow>{ar ? `ناقش ${item.label} معنا` : `Discuss ${item.label}`}</Button><Button href="#overview" size="lg" variant="onDarkGhost">{ar ? "اكتشف الاستشارة" : "Explore advisory"}</Button></div></Reveal></div></section>
    <Section id="overview" surface="paper" aria-labelledby="overview-heading"><div className="shell grid items-start gap-10 lg:grid-cols-[.85fr_1.15fr]"><Reveal><Marker>{ar ? "عن هذه الاستشارة" : "About this advisory"}</Marker><h2 id="overview-heading" className="mt-5 max-w-[15ch] text-d2 text-text">{ar ? "القرار المهم يستحق عملًا استشاريًا مركزًا." : "A focused decision deserves a focused engagement."}</h2><p className="measure mt-6 text-lead text-text-2">{detail.overview}</p><p className="measure mt-4 text-text-3">{detail.challenge}</p></Reveal><Reveal kind="right"><div className="overflow-hidden rounded-[var(--radius-lg)] border border-rule bg-white shadow-e2"><div className="relative aspect-[16/10]">{image && <Image src={image.src} alt={ar ? `تصور بصري حول ${item.label}` : image.alt} fill sizes="(min-width: 1024px) 52vw, 100vw" className="object-cover" />}</div><div className="p-6 sm:p-8"><ServiceIcon name={item.icon} className="size-7 text-accent" /><p className="mt-6 font-display text-2xl leading-tight font-semibold text-text sm:text-3xl">{ar ? "وضوح يستطيع فريقك العمل به." : "Clarity your team can act on."}</p><p className="mt-4 text-text-3">{ar ? "توجه مدروس وخيارات واضحة وطريق عملي نحو المرحلة التالية." : "A well-framed direction, transparent trade-offs, and a practical route to the next milestone."}</p></div></div></Reveal></div></Section>
    <Section surface="paper" aria-labelledby="outcomes-heading" className="consultancy-outcomes"><div className="shell"><Reveal className="max-w-3xl"><Marker>{ar ? "ما الذي ستحصل عليه" : "What you leave with"}</Marker><h2 id="outcomes-heading" className="mt-4 text-d2 text-text">{ar ? "وضوح جاهز للتحول إلى خطوات." : "Clarity that is ready to act on."}</h2></Reveal><RevealGroup as="ol" className="consultancy-outcomes__list mt-12">{detail.outcomes.map((outcome, index) => <RevealItem key={outcome} as="li"><div className="consultancy-outcomes__item"><span>{String(index + 1).padStart(2, "0")}</span><h3>{outcome}</h3></div></RevealItem>)}</RevealGroup></div></Section>
    <Section surface="ink"><div className="shell grid items-start gap-10 lg:grid-cols-[.72fr_1.28fr]"><Reveal><span className="font-mono text-marker font-medium tracking-[.16em] text-accent-bright uppercase">{ar ? "رأي أحد عملائنا" : "Client feedback"}</span><h2 className="mt-5 max-w-[12ch] text-d2 text-white">{ar ? "ثقة تظهر في التفاصيل." : "Trusted through the details."}</h2></Reveal><Reveal kind="right"><figure className="rounded-[var(--radius-lg)] border border-white/15 bg-white/[.05] p-8 sm:p-10"><Quote aria-hidden className="size-8 text-accent-bright" /><blockquote className="mt-6 font-display text-xl leading-snug text-white sm:text-2xl">{ar ? "أنجز فريق باراكود العمل قبل الموعد المحدد، وتجاوز توقعاتنا باستمرار. خبرتهم وحرصهم على الجودة جعلاهم شريكًا نثق به في أعمالنا." : "The Barakode team delivered ahead of schedule and consistently exceeded our expectations. Their expertise and commitment to quality have made them a trusted partner for our business."}</blockquote><figcaption className="mt-7 pt-2 text-sm text-ontext-2"><span className="block font-medium text-white">{ar ? "آدم لويس" : "Adam Lewis"}</span>{ar ? "المؤسس والرئيس التنفيذي، iConsult" : "Founder & CEO, iConsult"}</figcaption></figure></Reveal></div></Section>
    <Section surface="paper" aria-labelledby="focus-heading"><div className="shell"><Reveal><Marker>{ar ? "مجال تركيزنا" : "Where we focus"}</Marker><h2 id="focus-heading" className="mt-5 max-w-[15ch] text-d2 text-text">{ar ? "المؤشرات والفرق المرتبطة بهذا القرار." : "The signals and people around this decision."}</h2></Reveal><div className="mt-10 grid gap-8 lg:grid-cols-2"><RevealGroup as="ul" className="grid gap-3">{detail.signals.map((signal) => <RevealItem key={signal} as="li" className="rounded-[var(--radius-sm)] border border-rule bg-paper-raised p-5 text-text-2"><Check aria-hidden className="mr-3 inline size-4 text-accent" />{signal}</RevealItem>)}</RevealGroup><RevealGroup as="ul" className="grid gap-3">{detail.audience.map((audience) => <RevealItem key={audience} as="li" className="rounded-[var(--radius-sm)] border border-rule bg-paper-raised p-5 text-text-2"><ServiceIcon name={item.icon} className="mr-3 inline size-4 text-accent" />{audience}</RevealItem>)}</RevealGroup></div></div></Section>
    <Section surface="paper" aria-labelledby="approach-heading"><div className="shell grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><Reveal><Marker>{ar ? "نهجنا" : "Our approach"}</Marker><h2 id="approach-heading" className="mt-5 max-w-[13ch] text-d2 text-text">{ar ? "مسار منظم نحو قرار مدروس." : "A structured path to a defensible decision."}</h2></Reveal><RevealGroup as="ol" className="grid gap-3 sm:grid-cols-2">{detail.steps.map((step, index) => <RevealItem key={step.title} as="li" className="rounded-[var(--radius-md)] border border-rule bg-paper-raised p-5 shadow-e1"><span className="font-mono text-xs text-accent-ink">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-5 text-lg font-semibold text-text">{step.title}</h3><p className="mt-2 text-sm leading-relaxed text-text-3">{step.detail}</p></RevealItem>)}</RevealGroup></div></Section>
    <Section surface="paper" aria-labelledby="faq-heading"><div className="shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><Reveal><Marker>{ar ? "الأسئلة" : "Questions"}</Marker><h2 id="faq-heading" className="mt-5 max-w-[12ch] text-d2 text-text">{ar ? "إجابات عن التفاصيل العملية." : "The practical details, answered."}</h2><Button href={`/contact?intent=${slug}`} size="lg" className="mt-8" arrow>{ar ? "ابدأ الحديث معنا" : "Start a conversation"}</Button></Reveal><Reveal kind="right"><Accordion items={detail.faqs} /></Reveal></div></Section>
    {related.length > 0 && <Section surface="paper"><div className="shell"><Reveal><h2 className="max-w-[20ch] text-d3 text-text">{ar ? "اكتشف القرار التالي المرتبط بمشروعك." : "Explore the next connected decision."}</h2></Reveal><RevealGroup as="ul" className="mt-8 grid gap-3 md:grid-cols-3">{related.map(({ detail: relatedDetail, item: relatedItem }) => <RevealItem key={relatedItem.href} as="li"><Link href={relatedItem.href} className="group flex h-full items-center justify-between gap-5 rounded-[var(--radius-md)] border border-rule bg-white p-5 text-text shadow-e1 transition-[border-color,box-shadow,transform] duration-300 hover:-translate-y-0.5 hover:border-accent/60 hover:shadow-e2"><span><span className="block font-display font-semibold">{relatedItem.label}</span><span className="mt-1 block text-sm text-text-3">{relatedDetail.overview}</span></span><ArrowRight aria-hidden className="size-4 shrink-0 text-accent transition-transform group-hover:translate-x-1" /></Link></RevealItem>)}</RevealGroup></div></Section>}
    <JsonLd data={[serviceSchema({ name: item.label, description: detail.metaDescription, path: item.href }), breadcrumbSchema([{ name: ar ? "الرئيسية" : "Home", path: "/" }, { name: ar ? "الاستشارات" : "Consultancy", path: "/consultancy" }, { name: item.label, path: item.href }]), faqSchema(detail.faqs)]} />
  </div>;
}
